# Generated by Django 5.2.10 on 2026-01-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='isbn',
        ),
    ]
