# Generated by Django 5.2.10 on 2026-01-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_remove_aluno_email_remove_livro_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='matricula',
        ),
    ]
