# Generated by Django 5.2.10 on 2026-01-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_remove_aluno_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='autor',
            new_name='genero',
        ),
    ]
