# Generated by Django 5.2.10 on 2026-01-29 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_rename_autor_livro_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADICIONADO', 'Adicionado'), ('EMPRESTADO', 'Emprestado'), ('DEVOLVIDO', 'Devolvido'), ('EXCLUIDO', 'Excluído')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_acao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_acao'],
            },
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.livro'),
        ),
    ]
