# Generated by Django 5.2.10 on 2026-03-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_alter_livro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.CharField(default='Desconhecido', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='codigo_unico',
            field=models.CharField(default='TEMP', max_length=50),
            preserve_default=False,
        ),
    ]
