# Generated by Django 5.2.10 on 2026-03-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_alter_livro_codigo_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='codigo_unico',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
