# Generated by Django 5.2.10 on 2026-03-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_livro_ano_livro_editora_livro_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='codigo_unico',
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(default='TEMP', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
