# Generated by Django 5.2.10 on 2026-03-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_remove_livro_codigo_unico_alter_livro_isbn'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aluno',
            constraint=models.UniqueConstraint(fields=('nome', 'turma'), name='unique_aluno_por_turma'),
        ),
    ]
