# Generated by Django 5.2.10 on 2026-03-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0013_aluno_unique_aluno_por_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='tipo',
            field=models.CharField(choices=[('ADICIONADO', 'Adicionado'), ('ATUALIZADO', 'Atualizado'), ('EMPRESTADO', 'Emprestado'), ('DEVOLVIDO', 'Devolvido'), ('EXCLUIDO', 'Excluído')], max_length=20),
        ),
    ]
